packages:
  - docs
  - 'packages/*'

catalog:
  '@deviltea/eslint-config': 3.4.1
  '@deviltea/tsconfig': 0.0.6
  '@nuxt/kit': ^3.0.0
  '@nuxt/schema': ^3.0.0
  '@types/node': ^20
  '@types/micromatch': ^4.0.9
  '@vitest/coverage-v8': 2.1.3
  brotli-size: 4.0.0
  bumpp: 9.7.1
  csstype: 3.1.3
  eslint: 9.13.0
  fast-glob: 3.3.2
  gzip-size: 7.0.0
  happy-dom: 15.7.4
  jiti: 2.4.0
  local-pkg: 0.4.3
  magic-string: 0.30.12
  micromatch: 4.0.8
  pathe: 1.1.2
  perfect-debounce: 1.0.0
  prettier: 3.2.5
  publint: 0.2.11
  rimraf: 6.0.1
  terser: 5.36.0
  tsx: 4.19.1
  typescript: 5.6.3
  unbuild: 3.0.1
  unconfig: 0.5.5
  vite: 5.4.10
  vitest: 2.1.3
  vitepress: 1.5.0
  vue: 3.5.13
  zx: 8.2.0
